#!/bin/bash
# Incident Detection Script
# Triggered by Azure Monitor webhook or called manually
# Usage: bash scripts/incident-detect.sh --alert-type "Node NotReady" --cluster "prod-cluster" --nodes "node-worker-03,node-worker-05,node-worker-06"

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
INCIDENTS_DIR="$PROJECT_DIR/incidents/active"

# Parse arguments
ALERT_TYPE=""
CLUSTER=""
NODES=""
SEVERITY="P1"
DESCRIPTION=""

while [[ "$#" -gt 0 ]]; do
    case $1 in
        --alert-type) ALERT_TYPE="$2"; shift ;;
        --cluster) CLUSTER="$2"; shift ;;
        --nodes) NODES="$2"; shift ;;
        --severity) SEVERITY="$2"; shift ;;
        --description) DESCRIPTION="$2"; shift ;;
        *) echo "Unknown parameter: $1"; exit 1 ;;
    esac
    shift
done

if [ -z "$ALERT_TYPE" ] || [ -z "$CLUSTER" ]; then
    echo "Usage: bash incident-detect.sh --alert-type <type> --cluster <cluster> [--nodes <nodes>] [--severity <severity>] [--description <desc>]"
    exit 1
fi

# Create incidents directory
mkdir -p "$INCIDENTS_DIR"

# Generate incident ID and timestamp
INCIDENT_ID="INC-$(date +%Y%m%d-%H%M)"
TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
TIMESTAMP_ISO=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Create incident file
INCIDENT_FILE="$INCIDENTS_DIR/$INCIDENT_ID.md"

cat > "$INCIDENT_FILE" <<EOF
# $INCIDENT_ID — $ALERT_TYPE

**Cluster:** $CLUSTER
**Severity:** $SEVERITY
**Detected:** $TIMESTAMP
**Status:** ACTIVE

---

## Alert Details

**Type:** $ALERT_TYPE
**Cluster:** $CLUSTER
**Nodes Affected:** ${NODES:-"Unknown"}
**Description:** ${DESCRIPTION:-"No description provided"}

---

## Context

[Auto-generated by crisis-command-center]

### Similar Incidents
[Will be populated by similar-incidents.sh]

### Decision Support
[Will be populated by decision-support.sh]

### Precedent Decisions
[Will be populated from context graph]

---

## Actions

[Log actions taken here]

---

## Resolution

[Fill in when resolved]

---

## Metadata

- **Created:** $TIMESTAMP_ISO
- **Created By:** crisis-command-center
- **Source:** Azure Monitor
EOF

echo "✅ Incident created: $INCIDENT_FILE"
echo "   Incident ID: $INCIDENT_ID"
echo "   Next: Run './scripts/launch-dashboard.sh $INCIDENT_ID'"
